# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from satgonetem.proto import netem_pb2 as satgonetem_dot_proto_dot_netem__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in satgonetem/proto/netem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NetemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServerGetVersion = channel.unary_unary(
                '/netem.Netem/ServerGetVersion',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.VersionResponse.FromString,
                _registered_method=True)
        self.ServerPullImages = channel.unary_stream(
                '/netem.Netem/ServerPullImages',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.PullSrvMsg.FromString,
                _registered_method=True)
        self.ServerCleanContainers = channel.unary_unary(
                '/netem.Netem/ServerCleanContainers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)
        self.ProjectGetMany = channel.unary_unary(
                '/netem.Netem/ProjectGetMany',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.PrjListResponse.FromString,
                _registered_method=True)
        self.ProjectOpen = channel.unary_unary(
                '/netem.Netem/ProjectOpen',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.OpenRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.PrjOpenResponse.FromString,
                _registered_method=True)
        self.ProjectClose = channel.unary_stream(
                '/netem.Netem/ProjectClose',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.ProjectCloseMsg.FromString,
                _registered_method=True)
        self.ProjectSave = channel.unary_stream(
                '/netem.Netem/ProjectSave',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.ProjectSaveMsg.FromString,
                _registered_method=True)
        self.ProjectGetNodeConfigs = channel.unary_unary(
                '/netem.Netem/ProjectGetNodeConfigs',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.FileResponse.FromString,
                _registered_method=True)
        self.ProjectGetStatus = channel.unary_unary(
                '/netem.Netem/ProjectGetStatus',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ReadNetworkFile = channel.unary_unary(
                '/netem.Netem/ReadNetworkFile',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.FileResponse.FromString,
                _registered_method=True)
        self.WriteNetworkFile = channel.unary_unary(
                '/netem.Netem/WriteNetworkFile',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.WNetworkRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)
        self.TopologyCheck = channel.unary_unary(
                '/netem.Netem/TopologyCheck',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)
        self.TopologyReload = channel.unary_stream(
                '/netem.Netem/TopologyReload',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.TopologyRunMsg.FromString,
                _registered_method=True)
        self.TopologyRun = channel.unary_stream(
                '/netem.Netem/TopologyRun',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.TopologyRunMsg.FromString,
                _registered_method=True)
        self.TopologyStartAll = channel.unary_unary(
                '/netem.Netem/TopologyStartAll',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)
        self.TopologyStopAll = channel.unary_unary(
                '/netem.Netem/TopologyStopAll',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)
        self.NodeReadConfigFiles = channel.unary_unary(
                '/netem.Netem/NodeReadConfigFiles',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.NodeRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.ConfigFilesResponse.FromString,
                _registered_method=True)
        self.NodeStart = channel.unary_unary(
                '/netem.Netem/NodeStart',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.NodeRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)
        self.NodeStop = channel.unary_unary(
                '/netem.Netem/NodeStop',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.NodeRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)
        self.NodeRestart = channel.unary_unary(
                '/netem.Netem/NodeRestart',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.NodeRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)
        self.NodeSetIfState = channel.unary_unary(
                '/netem.Netem/NodeSetIfState',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.NodeIfStateRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)
        self.NodeCapture = channel.unary_stream(
                '/netem.Netem/NodeCapture',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.NodeInterfaceRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.CaptureSrvMsg.FromString,
                _registered_method=True)
        self.NodeCopyFrom = channel.unary_stream(
                '/netem.Netem/NodeCopyFrom',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.CopyMsg.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.CopyMsg.FromString,
                _registered_method=True)
        self.NodeCopyTo = channel.stream_unary(
                '/netem.Netem/NodeCopyTo',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.CopyMsg.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)
        self.NodeGetConsoleCmd = channel.unary_unary(
                '/netem.Netem/NodeGetConsoleCmd',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.ConsoleCmdRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.ConsoleCmdResponse.FromString,
                _registered_method=True)
        self.NodeRun = channel.unary_unary(
                '/netem.Netem/NodeRun',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.NodeRunRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.NodeRunResponse.FromString,
                _registered_method=True)
        self.NodeExec = channel.stream_stream(
                '/netem.Netem/NodeExec',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.ExecCltMsg.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.ExecSrvMsg.FromString,
                _registered_method=True)
        self.LinkUpdate = channel.unary_unary(
                '/netem.Netem/LinkUpdate',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.LinkRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)
        self.LinkAdd = channel.unary_unary(
                '/netem.Netem/LinkAdd',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.LinkRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)
        self.LinkDel = channel.unary_unary(
                '/netem.Netem/LinkDel',
                request_serializer=satgonetem_dot_proto_dot_netem__pb2.LinkRequest.SerializeToString,
                response_deserializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
                _registered_method=True)


class NetemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ServerGetVersion(self, request, context):
        """Server actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerPullImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerCleanContainers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProjectGetMany(self, request, context):
        """Project actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProjectOpen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProjectClose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProjectSave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProjectGetNodeConfigs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProjectGetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadNetworkFile(self, request, context):
        """Read/Write network topology
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteNetworkFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TopologyCheck(self, request, context):
        """topology actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TopologyReload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TopologyRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TopologyStartAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TopologyStopAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeReadConfigFiles(self, request, context):
        """Node actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeRestart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeSetIfState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeCapture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeCopyFrom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeCopyTo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeGetConsoleCmd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeExec(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkUpdate(self, request, context):
        """Link actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkDel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ServerGetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerGetVersion,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.VersionResponse.SerializeToString,
            ),
            'ServerPullImages': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerPullImages,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.PullSrvMsg.SerializeToString,
            ),
            'ServerCleanContainers': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerCleanContainers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
            'ProjectGetMany': grpc.unary_unary_rpc_method_handler(
                    servicer.ProjectGetMany,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.PrjListResponse.SerializeToString,
            ),
            'ProjectOpen': grpc.unary_unary_rpc_method_handler(
                    servicer.ProjectOpen,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.OpenRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.PrjOpenResponse.SerializeToString,
            ),
            'ProjectClose': grpc.unary_stream_rpc_method_handler(
                    servicer.ProjectClose,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.ProjectCloseMsg.SerializeToString,
            ),
            'ProjectSave': grpc.unary_stream_rpc_method_handler(
                    servicer.ProjectSave,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.ProjectSaveMsg.SerializeToString,
            ),
            'ProjectGetNodeConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.ProjectGetNodeConfigs,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.FileResponse.SerializeToString,
            ),
            'ProjectGetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ProjectGetStatus,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.StatusResponse.SerializeToString,
            ),
            'ReadNetworkFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadNetworkFile,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.FileResponse.SerializeToString,
            ),
            'WriteNetworkFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteNetworkFile,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.WNetworkRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
            'TopologyCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.TopologyCheck,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
            'TopologyReload': grpc.unary_stream_rpc_method_handler(
                    servicer.TopologyReload,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.TopologyRunMsg.SerializeToString,
            ),
            'TopologyRun': grpc.unary_stream_rpc_method_handler(
                    servicer.TopologyRun,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.TopologyRunMsg.SerializeToString,
            ),
            'TopologyStartAll': grpc.unary_unary_rpc_method_handler(
                    servicer.TopologyStartAll,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
            'TopologyStopAll': grpc.unary_unary_rpc_method_handler(
                    servicer.TopologyStopAll,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
            'NodeReadConfigFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeReadConfigFiles,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.NodeRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.ConfigFilesResponse.SerializeToString,
            ),
            'NodeStart': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeStart,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.NodeRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
            'NodeStop': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeStop,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.NodeRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
            'NodeRestart': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeRestart,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.NodeRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
            'NodeSetIfState': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeSetIfState,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.NodeIfStateRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
            'NodeCapture': grpc.unary_stream_rpc_method_handler(
                    servicer.NodeCapture,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.NodeInterfaceRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.CaptureSrvMsg.SerializeToString,
            ),
            'NodeCopyFrom': grpc.unary_stream_rpc_method_handler(
                    servicer.NodeCopyFrom,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.CopyMsg.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.CopyMsg.SerializeToString,
            ),
            'NodeCopyTo': grpc.stream_unary_rpc_method_handler(
                    servicer.NodeCopyTo,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.CopyMsg.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
            'NodeGetConsoleCmd': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeGetConsoleCmd,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.ConsoleCmdRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.ConsoleCmdResponse.SerializeToString,
            ),
            'NodeRun': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeRun,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.NodeRunRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.NodeRunResponse.SerializeToString,
            ),
            'NodeExec': grpc.stream_stream_rpc_method_handler(
                    servicer.NodeExec,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.ExecCltMsg.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.ExecSrvMsg.SerializeToString,
            ),
            'LinkUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkUpdate,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.LinkRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
            'LinkAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkAdd,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.LinkRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
            'LinkDel': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkDel,
                    request_deserializer=satgonetem_dot_proto_dot_netem__pb2.LinkRequest.FromString,
                    response_serializer=satgonetem_dot_proto_dot_netem__pb2.AckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'netem.Netem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('netem.Netem', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Netem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ServerGetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/ServerGetVersion',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerPullImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/netem.Netem/ServerPullImages',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.PullSrvMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerCleanContainers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/ServerCleanContainers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProjectGetMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/ProjectGetMany',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.PrjListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProjectOpen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/ProjectOpen',
            satgonetem_dot_proto_dot_netem__pb2.OpenRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.PrjOpenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProjectClose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/netem.Netem/ProjectClose',
            satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.ProjectCloseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProjectSave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/netem.Netem/ProjectSave',
            satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.ProjectSaveMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProjectGetNodeConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/ProjectGetNodeConfigs',
            satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProjectGetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/ProjectGetStatus',
            satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadNetworkFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/ReadNetworkFile',
            satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteNetworkFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/WriteNetworkFile',
            satgonetem_dot_proto_dot_netem__pb2.WNetworkRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TopologyCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/TopologyCheck',
            satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TopologyReload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/netem.Netem/TopologyReload',
            satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.TopologyRunMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TopologyRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/netem.Netem/TopologyRun',
            satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.TopologyRunMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TopologyStartAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/TopologyStartAll',
            satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TopologyStopAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/TopologyStopAll',
            satgonetem_dot_proto_dot_netem__pb2.ProjectRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeReadConfigFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/NodeReadConfigFiles',
            satgonetem_dot_proto_dot_netem__pb2.NodeRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.ConfigFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/NodeStart',
            satgonetem_dot_proto_dot_netem__pb2.NodeRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/NodeStop',
            satgonetem_dot_proto_dot_netem__pb2.NodeRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeRestart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/NodeRestart',
            satgonetem_dot_proto_dot_netem__pb2.NodeRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeSetIfState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/NodeSetIfState',
            satgonetem_dot_proto_dot_netem__pb2.NodeIfStateRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/netem.Netem/NodeCapture',
            satgonetem_dot_proto_dot_netem__pb2.NodeInterfaceRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.CaptureSrvMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeCopyFrom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/netem.Netem/NodeCopyFrom',
            satgonetem_dot_proto_dot_netem__pb2.CopyMsg.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.CopyMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeCopyTo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/netem.Netem/NodeCopyTo',
            satgonetem_dot_proto_dot_netem__pb2.CopyMsg.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeGetConsoleCmd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/NodeGetConsoleCmd',
            satgonetem_dot_proto_dot_netem__pb2.ConsoleCmdRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.ConsoleCmdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/NodeRun',
            satgonetem_dot_proto_dot_netem__pb2.NodeRunRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.NodeRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeExec(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/netem.Netem/NodeExec',
            satgonetem_dot_proto_dot_netem__pb2.ExecCltMsg.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.ExecSrvMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/LinkUpdate',
            satgonetem_dot_proto_dot_netem__pb2.LinkRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/LinkAdd',
            satgonetem_dot_proto_dot_netem__pb2.LinkRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkDel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netem.Netem/LinkDel',
            satgonetem_dot_proto_dot_netem__pb2.LinkRequest.SerializeToString,
            satgonetem_dot_proto_dot_netem__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
