from satgonetem.routing.base_daemon import RoutingDaemon
from satgonetem.routing.ospf_daemon import OSPFDaemon
from satgonetem.routing.static_daemon import StaticRoutingDaemon
from satgonetem.routing.srmpls_daemon import SRMPLSDaemon
from satgonetem.routing.isis_sr_bird_daemon import ISISBirdSRDaemon
